### PR TITLE
impr(Documentation): Formatting

### PR DESCRIPTION
**Pull request by quentin-sommer**
## Formatting improvements

- Addded save option to npm install commands

Also IMO the `ap` name is very close to traditional express-like servers `app` in the node.js community and might be confusing. How about changing it to something else? For example `phone`, `aphone`, `aircallPhone`

image

- [x] Your branch is based on `master`
- [x] Your code is unit tested
- [x] CircleCI builds are green (coverage and lint)
- [x] Add team "CTI" as "Reviewer" for the PR
- [x] Name your PR with the convention `fix|feat|impr(<subject>): description`.

### CODE REVIEW

**Comment by hereismass** [comment]
Good idea :) 
Something as simple as `phone` can do the trick. 
I can do it if you want

**Comment by quentin-sommer** [comment]
As you want! I have time to do it too if you're busy

**Comment by quentin-sommer** [comment]
@hereismass Ready to be reviewed!

**Comment by quentin-sommer** [comment]
ping @hereismass can we ship this 😃?

**Pull request merged**
